# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogNorm <- function(data, scale_factor = 10000L) {
    .Call(`_scPort_LogNorm`, data, scale_factor)
}

clr_norm_rcpp <- function(mat) {
    .Call(`_scPort_clr_norm_rcpp`, mat)
}

SparseRowVarStd_rcpp <- function(mat, mu, sd, vmax) {
    .Call(`_scPort_SparseRowVarStd_rcpp`, mat, mu, sd, vmax)
}

regress_out_matrix_rcpp <- function(mat, qr) {
    .Call(`_scPort_regress_out_matrix_rcpp`, mat, qr)
}

FastSparseRowScale_rcpp <- function(mat, scale = TRUE, center = TRUE, scale_max = 10) {
    .Call(`_scPort_FastSparseRowScale_rcpp`, mat, scale, center, scale_max)
}

