# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogNorm <- function(data, scale_factor = 10000L) {
    .Call(`_scPort_LogNorm`, data, scale_factor)
}

